// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6JX3-Mm3w51ZJPiNYYVRZcm4f16XLKN0',
    appId: '1:481548549402:web:a5e68b43b913d98c2840a3',
    messagingSenderId: '481548549402',
    projectId: 'salon-77356',
    authDomain: 'salon-77356.firebaseapp.com',
    storageBucket: 'salon-77356.firebasestorage.app',
    measurementId: 'G-4TGDR6JMMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxK5k-N36gycs62mZ3g_b9MLeViDu9Ttg',
    appId: '1:181414733708:android:828164f6d5464f7716d8a9',
    messagingSenderId: '181414733708',
    projectId: 'salon-base',
    storageBucket: 'salon-base.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7TT5iUP7-fZ7LvAGEcOi-sUeme_wL5IU',
    appId: '1:181414733708:ios:58ac946d968dec0e16d8a9',
    messagingSenderId: '181414733708',
    projectId: 'salon-base',
    storageBucket: 'salon-base.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

}