// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6JX3-Mm3w51ZJPiNYYVRZcm4f16XLKN0',
    appId: '1:481548549402:web:a5e68b43b913d98c2840a3',
    messagingSenderId: '481548549402',
    projectId: 'salon-77356',
    authDomain: 'salon-77356.firebaseapp.com',
    storageBucket: 'salon-77356.firebasestorage.app',
    measurementId: 'G-4TGDR6JMMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBQAHc5jro0VWfLSa3AFr4t0B2SLyAPMs',
    appId: '1:481548549402:android:362c8104cf8633fc2840a3',
    messagingSenderId: '481548549402',
    projectId: 'salon-77356',
    storageBucket: 'salon-77356.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChr-Y0wyY3Q_t-NEq-57daIOhmFk9ztVI',
    appId: '1:481548549402:ios:fe4650a1cff19b072840a3',
    messagingSenderId: '481548549402',
    projectId: 'salon-77356',
    storageBucket: 'salon-77356.firebasestorage.app',
    iosBundleId: 'com.example.salon',
  );
}
